print("enter name of student")
n=input()
print("enter four mark")
m1=int(input())
m2=int(input())
m3=int(input())
m4=int(input())
s=m1+m2+m3+m4
avg=s/4
print("name=",n)
print("mark1=",m1)
print("mark2=",m2)
print("mark3=",m3)
print("mark4=",m4)
print("sum of all marks=",s)
print("average of mark=",avg)
