print("enter principal amount")
p=int(input())
print("enter rate of interest")
r=int(input())
print("enter time")
t=int(input())
si=p*r*t/100
print("principal amount=",p)
print("rate of interest=",r)
print("time=",t)
print("simple interest=",si)
