print("enter two number")
no1=int(input("first number"))
no2=int(input("second number"))
print("enter your choice\n1.add\n2.sub\n3.mult")
ch=int(input())
match ch:
    case 1:print("result=",no1+no2)
    case 2:print("result=",no1-no2)
    case 3:print("result=",no1*no2)
    case _:print("invalid choice")